version: "3.7"

#networks:
  #my_network:
    #external: true

services:
  database:
    image: mysql:8.0
    platform: linux/amd64
    command:
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=codetest
      - MYSQL_USER=codetest
      - MYSQL_PASSWORD=swordfish
    ports:
      - "3307:3307"
    restart: always
    #networks:
      #- my_network

  schema_app:
    build:
      context: ./images/schema_app
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    links:
      - database
    depends_on:
      - database
    command: ["./app.py"]
    #networks:
      #- my_network